In [1]:
import numpy as np

In [2]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
lista = [10, 20, "hello", 30.3, True]
lista

[10, 20, 'hello', 30.3, True]

In [ ]:
np.array(lista)

array(['10', '20', 'hello', '30.3', 'True'], dtype='<U32')

In [10]:
lista = [10, 20, "hello", 30.3, True]
array = np.array(lista)
type(array), array, array.dtype

(numpy.ndarray,
 array(['10', '20', 'hello', '30.3', 'True'], dtype='<U32'),
 dtype('<U32'))

In [11]:
lista = [10, 20, 30.3, True]
array = np.array(lista)
type(array), array, array.dtype

(numpy.ndarray, array([10. , 20. , 30.3,  1. ]), dtype('float64'))

In [12]:
lista = [10, 20, 30, True]
array = np.array(lista)
type(array), array, array.dtype

(numpy.ndarray, array([10, 20, 30,  1]), dtype('int64'))

In [13]:
lista = [10, 20, 30, True]
array = np.array(lista, dtype=np.int8)
type(array), array, array.dtype

(numpy.ndarray, array([10, 20, 30,  1], dtype=int8), dtype('int8'))

In [14]:
2 ** 8

256

In [15]:
bin(256)

'0b100000000'

In [16]:
bin(255)

'0b11111111'

In [18]:
lista = [10, 20, 30, 255]
array = np.array(lista, dtype=np.uint8)
type(array), array, array.dtype

(numpy.ndarray, array([ 10,  20,  30, 255], dtype=uint8), dtype('uint8'))

In [19]:
lista = [10, 20, 30, 255 // 2]
array = np.array(lista, dtype=np.int8)
type(array), array, array.dtype

(numpy.ndarray, array([ 10,  20,  30, 127], dtype=int8), dtype('int8'))

In [20]:
lista = [10, 20, 30, 255 // 2, -128]
array = np.array(lista, dtype=np.int8)
type(array), array, array.dtype

(numpy.ndarray,
 array([  10,   20,   30,  127, -128], dtype=int8),
 dtype('int8'))

In [22]:
lista = [10, 20, 30, 255 // 2, -127]
array = np.array(lista, dtype=np.int8)
type(array), array, array.dtype

(numpy.ndarray,
 array([  10,   20,   30,  127, -127], dtype=int8),
 dtype('int8'))

In [23]:
lista = [2, 3, [5, 6]]
lista

[2, 3, [5, 6]]

In [26]:
lista = [[2, 3], [5, 6]]
array = np.array(lista)
array

array([[2, 3],
       [5, 6]])

In [27]:
lista = [[2, 3], [5, 6]]
array = np.array(lista)
array, array.shape

(array([[2, 3],
        [5, 6]]),
 (2, 2))

In [28]:
lista = [[2, 3], [5, 6], [7, 9]]
array = np.array(lista)
array, array.shape

(array([[2, 3],
        [5, 6],
        [7, 9]]),
 (3, 2))

In [30]:
lista = [[2, 3], [5, 6], [7, None]]
array = np.array(lista)
array, array.shape

(array([[2, 3],
        [5, 6],
        [7, None]], dtype=object),
 (3, 2))

In [31]:
lista = [[2, 3], [5, 6], [7, None]]
array = np.array(lista)
array.flatten()

array([2, 3, 5, 6, 7, None], dtype=object)

In [34]:
lista = [[2, 3], [5, 6], [7, None]]
array = np.array(lista)
array = array.reshape((2, 3))
array, array.shape

(array([[2, 3, 5],
        [6, 7, None]], dtype=object),
 (2, 3))

In [36]:
lista = [[2, 3], [5, 6], [7, None]]
array = np.array(lista)
array = array.reshape((2, 3))
array, array.shape

(array([[2, 3, 5],
        [6, 7, None]], dtype=object),
 (2, 3))