In [4]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

In [8]:
date = np.array([65, 75, 80, 95, 120, 205, 400])


In [7]:
date

array([ 65,  75,  80,  95, 120, 205, 400])

In [6]:
date.reshape((-1, 1))

array([[ 65],
       [ 75],
       [ 80],
       [ 95],
       [120],
       [205],
       [400]])

In [9]:
scaler = MinMaxScaler()
scaler.fit_transform(date.reshape((-1, 1)))

array([[0.        ],
       [0.02985075],
       [0.04477612],
       [0.08955224],
       [0.1641791 ],
       [0.41791045],
       [1.        ]])

In [10]:
scaler = StandardScaler()
scaler.fit_transform(date.reshape((-1, 1)))

array([[-0.74883163],
       [-0.65922785],
       [-0.61442595],
       [-0.48002028],
       [-0.25601081],
       [ 0.50562136],
       [ 2.25289516]])