In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits

# Intro to tensorflow

In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.18.0'

In [5]:
numere = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
tf.constant(numere)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [7]:
numere = tf.constant([1,2,3,4,5,6,7,8,9,10], dtype=tf.float64)
numere

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])>

In [8]:
zero_tensor = tf.zeros(shape=(3,3))
zero_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
zero_tensor = tf.ones(shape=(3,3))
zero_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
zero_tensor = tf.fill(dims=(2,3), value=4.4)
zero_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4.4, 4.4, 4.4],
       [4.4, 4.4, 4.4]], dtype=float32)>

In [11]:
tf.random.normal(shape=(3,3), mean=0, stddev=1.0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.83485895,  1.5987476 , -2.2723472 ],
       [ 2.3410795 , -0.8213093 ,  2.8982844 ],
       [ 0.11292224,  0.27392784,  1.8182012 ]], dtype=float32)>

In [12]:
tf.random.uniform(shape=(5, 2), minval=1, maxval=10)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[3.445091 , 1.6662178],
       [2.3523827, 3.9608722],
       [7.9265504, 2.9383755],
       [3.506311 , 4.3183603],
       [7.412533 , 1.7904652]], dtype=float32)>

In [13]:
zero_tensor = tf.fill(dims=(2,3), value=2.)


one_tensor = tf.fill(dims=(3,2), value=1.5)
one_tensor, zero_tensor

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1.5, 1.5],
        [1.5, 1.5],
        [1.5, 1.5]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[2., 2., 2.],
        [2., 2., 2.]], dtype=float32)>)

In [14]:
numere = tf.constant([1,2,3,4,5,6,7,8,9,10], dtype=tf.float64)
numere

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])>

In [15]:
variabila_tf = tf.Variable(numere)
variabila_tf

<tf.Variable 'Variable:0' shape=(10,) dtype=float64, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])>

In [16]:
variabila_tf.assign_add([1,1,1,1,1,1,1,1,1,1])

<tf.Variable 'UnreadVariable' shape=(10,) dtype=float64, numpy=array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])>

In [17]:
variabila_tf

<tf.Variable 'Variable:0' shape=(10,) dtype=float64, numpy=array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])>

In [18]:
variabila_tf.assign_add([1,1,1,1,1,1,1,1,1,1])

<tf.Variable 'UnreadVariable' shape=(10,) dtype=float64, numpy=array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])>

In [19]:
variabila_tf.assign([20,20,1,1,1,33,1,44,1,1])

<tf.Variable 'UnreadVariable' shape=(10,) dtype=float64, numpy=array([20., 20.,  1.,  1.,  1., 33.,  1., 44.,  1.,  1.])>

In [20]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [21]:
with tf.device("CPU:0"):
  print("Acest model ruleaza pe CPU")

Acest model ruleaza pe CPU


In [22]:
with tf.device("GPU:0"):
  print("Acest model ruleaza pe GPU")

Acest model ruleaza pe GPU


# In colab Executie -> schimbati tipul executiei

In [23]:
variabila_tf

<tf.Variable 'Variable:0' shape=(10,) dtype=float64, numpy=array([20., 20.,  1.,  1.,  1., 33.,  1., 44.,  1.,  1.])>