In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4, 5]
print(l)

[1, 2, 3, 4, 5]


In [4]:
l + [1]

[1, 2, 3, 4, 5, 1]

In [5]:
l  + l

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
l * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
l

[1, 2, 3, 4, 5]

In [9]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [10]:
arr + 1

array([2, 3, 4, 5, 6])

In [11]:
arr 

array([1, 2, 3, 4, 5])

In [12]:
arr += 100

In [13]:
arr

array([101, 102, 103, 104, 105])

In [14]:
arr * arr

array([10201, 10404, 10609, 10816, 11025])

In [17]:
l = [1, 2, 3, 4, 5]
l * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [19]:
new_l = []
l = [1, 2, 3, 4, 5]
for i in l:
    new_l.append(i ** 2)
new_l

[1, 4, 9, 16, 25]

In [20]:

l = [1, 2, 3, 4, 5]

new_l = [i ** 2 for i in l]

new_l

[1, 4, 9, 16, 25]

In [21]:

l = [1, 2, 3, 4, 5]

new_l = [i ** 2 for i in l if i > 2]

new_l

[9, 16, 25]

In [22]:
l = [1, 2, 3, 4, 5]
list(map(lambda x: x ** 2 ,l))

[1, 4, 9, 16, 25]

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr ** 2

array([ 1,  4,  9, 16, 25])

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr > 3


array([False, False, False,  True,  True])

In [25]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 3]

array([4, 5])

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 121, 32, 41])
print(arr[arr > 3])
print(arr[arr < 11])

[  4   5   6   7   8   8   9  10  11 121  32  41]
[ 1  2  3  4  5  6  7  8  8  9 10]


In [27]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   8,   9,  10,  11, 121,
        32,  41])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 121, 32, 41])
print(arr[(arr > 3)  & (arr < 11)])

[ 4  5  6  7  8  8  9 10]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 121, 32, 41])
cond1 = arr > 3
cond2 = arr < 11
print(arr[cond1  & cond2])

[ 4  5  6  7  8  8  9 10]


In [33]:
np.array((1, 2, 3, 4))

array([1, 2, 3, 4])

In [34]:
np.array(range(33, 44))

array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [35]:
np.arange(33, 44)

array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [36]:
np.arange(33, 44, 3)

array([33, 36, 39, 42])

In [37]:
np.arange(100, 4, 3)

array([], dtype=int64)

In [38]:
np.arange(100, 4, -3)

array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52,  49,  46,  43,  40,  37,  34,  31,  28,  25,
        22,  19,  16,  13,  10,   7])

In [41]:
np.arange(1, 100).reshape(33, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48],
       [49, 50, 51],
       [52, 53, 54],
       [55, 56, 57],
       [58, 59, 60],
       [61, 62, 63],
       [64, 65, 66],
       [67, 68, 69],
       [70, 71, 72],
       [73, 74, 75],
       [76, 77, 78],
       [79, 80, 81],
       [82, 83, 84],
       [85, 86, 87],
       [88, 89, 90],
       [91, 92, 93],
       [94, 95, 96],
       [97, 98, 99]])