In [1]:
import random

In [2]:
random.random()

0.029504486497344606

In [3]:
random.random()

0.8725047489357965

In [4]:
random.randint(1, 10)

10

In [5]:
random.randint(1, 10)

8

In [6]:
import numpy as np

In [7]:
np.random.random()

0.1717124371516292

In [8]:
np.random.randint(1, 10)

8

In [9]:
np.random.randint(1, 10, 10)

array([9, 7, 2, 2, 3, 2, 6, 3, 6, 9])

In [10]:
np.random.randint(1, 10, (2, 2))

array([[9, 7],
       [2, 7]])

In [12]:
array = np.random.randint(1, 10, (2, 2))
array, type(array), array.shape, array.dtype

(array([[7, 7],
        [1, 9]]),
 numpy.ndarray,
 (2, 2),
 dtype('int64'))

In [13]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.random.randint(1, 10, 5)

array([3, 1, 9, 9, 2])

In [15]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
x_y = 10