In [1]:
import numpy as np

In [2]:
input_reale = np.array([1, 0, 0, 1])
input_prezise = np.array([0, 0, 0, 0])


In [3]:
input_reale - input_prezise

array([1, 0, 0, 1])

In [4]:
input_prezise - input_reale 

array([-1,  0,  0, -1])

In [5]:
(input_reale - input_prezise) ** 2

array([1, 0, 0, 1])

In [ ]:
(input_prezise - input_reale ) ** 2

array([1, 0, 0, 1])

In [7]:
np.sum((input_prezise - input_reale ) ** 2)

np.int64(2)

In [8]:
np.mean((input_prezise - input_reale ) ** 2)

np.float64(0.5)

In [9]:
def mse_loss(y_real, y_prezis):
    return np.mean((y_real - y_prezis ) ** 2)